### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es6.object.define-property'

### ISSUE THREAD

**Issue by serhatv** [aichbauer/express-rest-api-boilerplate#37]
I've just encountered a problem while `yarn start` command. Google searches says it's related with babel but solutions they offered didn't work. 

Ubuntu 19.04
latest npm and node

whole log:

```
> express-rest-api-boilerplate@0.0.0 dev /home/srht/Codes/birebir/bb-server_2
> cross-env NODE_ENV=development node ./api/api.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es6.object.define-property'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/srht/Codes/birebir/bb-server_2/node_modules/express-routes-mapper/lib/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-rest-api-boilerplate@0.0.0 dev: `cross-env NODE_ENV=development node ./api/api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the express-rest-api-boilerplate@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/srht/.npm/_logs/2019-06-21T10_32_25_035Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by anjil** [comment]
@serhatv Please check https://github.com/aichbauer/express-rest-api-boilerplate/issues/38

**Comment by aichbauer** [comment]
@serhatv please check if the issue from @anjil helps you... If not we will take a closer look into that issue...

**Comment by serhatv** [comment]
thanks, I haven't tried it yet, I'll share the result.

**Comment by aichbauer** [comment]
#39
